apiVersion: 1

deleteDatasources:
    - name: Graphite
      orgId: 1  

datasources:
  - name: Loki
    type: loki
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      derivedFields:
        # Field with internal link pointing to datasource in Grafana
        - datasourceUid: my_jaeger_uid
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          # url will be interpreted as query for the datasource
          url: "$${__value.raw}"

        # Field with external link
        - matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: "http://jaeger:16686/trace/$${__value.raw}"

  - name: InfluxDB - telegraf
    type: influxdb
    database: telegraf
    user: telegraf
    password: instrument
    url: http://influxdb:8086
    jsonData:
      httpMode: POST